language: python

python:
  - "2.7"

# following https://github.com/rocker-org/rocker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qqy linux-image-virtual linux-image-extra-virtual libxml2-dev libcurl4-openssl-dev curl python-pip r-base r-base-dev gdebi-core htop ncdu slirp
  - sudo pip install --upgrade virtualenvwrapper datacats pip pep8 pylint
  - wget -qO- https://get.docker.com/ | sh
  - sudo usermod -aG docker "$USER"
  - git clone git://github.com/cptactionhank/sekexe
  
before_script:
  - "sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d -H tcp://0.0.0.0:2375' &"
  - "while ! docker info &> /dev/null ; do sleep 1; done"

install: 
  #- datacats pull
  - echo hello
  
test:
  #- datacats create testcat
  #- datacats stop testcat
  #- datacats start testcat 8999
  #- 'curl 127.0.0.1:8999'
  #- datacats stop testcat
  - sudo docker run --rm -ti rocker/ropensci  
  
notifications:
  email: false  
  